"""reports json columns not null

Revision ID: 87a0fd60c5e5
Revises: 9b37652115ab
Create Date: 2026-07-01 16:38:09.893194

Adds NOT NULL to four `reports` JSON columns (`compliance_results`,
`processing_metadata`, `warnings`, `sources`) to match DATABASE_PLAN.md's
"Not null, default []" spec and `db/models.py`'s `default_factory=list`
semantics -- see that module's docstring for the full rationale.

SQLite has no `ALTER TABLE ... ALTER COLUMN`, so this must go through
Alembic's batch mode (recreates the table under the hood) rather than the
plain `op.alter_column(...)` autogenerate produced -- verified by running
the autogenerated version directly against SQLite first, which failed with
`OperationalError: near "ALTER": syntax error`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '87a0fd60c5e5'
down_revision: Union[str, Sequence[str], None] = '9b37652115ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('reports') as batch_op:
        batch_op.alter_column('compliance_results', existing_type=sa.JSON(), nullable=False)
        batch_op.alter_column('processing_metadata', existing_type=sa.JSON(), nullable=False)
        batch_op.alter_column('warnings', existing_type=sa.JSON(), nullable=False)
        batch_op.alter_column('sources', existing_type=sa.JSON(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('reports') as batch_op:
        batch_op.alter_column('sources', existing_type=sa.JSON(), nullable=True)
        batch_op.alter_column('warnings', existing_type=sa.JSON(), nullable=True)
        batch_op.alter_column('processing_metadata', existing_type=sa.JSON(), nullable=True)
        batch_op.alter_column('compliance_results', existing_type=sa.JSON(), nullable=True)
